name: Build, Test and Deploy to S3

on:
  push:
    branches:
      - main # Triggered only on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto' # Amazon Corretto

      # 3. Run the tests with maximum logging (debug mode)
      - name: Create minimal settings.xml
        run: echo "<settings></settings>" > ~/.m2/settings.xml

      - name: Create empty settings-security.xml
        run: echo "<settingsSecurity><master></master></settingsSecurity>" > ~/.m2/settings-security.xml

      - name: Run tests with maximum logging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: mvn clean test -X

      # 4. If tests pass, build the JAR
      - name: Build JAR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: mvn clean install -X -Dsettings.security=/dev/null

      # 5. Upload the JAR to S3
      - name: Upload JAR to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp target/amonkeys-0.0.1-SNAPSHOT.jar s3://amonkeys-photos/

      # Paso 6: Connect y Deploy to EC2

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/amonkeys.pem
          chmod 600 ~/.ssh/amonkeys.pem

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/amonkeys.pem ec2-user@$(aws ec2 describe-instances --region eu-north-1 --query "Reservations[0].Instances[0].PublicIpAddress" --output text) << 'EOF'
            cd /home/ec2-user
            aws s3 cp s3://amonkeys-photos/amonkeys-0.0.1-SNAPSHOT.jar /home/ec2-user/amonkeys-0.0.1-SNAPSHOT.jar
            java -jar /home/ec2-user/amonkeys-0.0.1-SNAPSHOT.jar &
          EOF
